### ISSUE TITLE
[worker-api] support signing in extension

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-js#108]
the polkadot/api allows to sign extrinsics using browser extensions:
```
web3FromAddress.....
.signAndSend(
          accountStore.getAddress,
          { signer: injector.signer },
          txResHandler,
        )
        .catch(txErrHandler);
```
using `@polkadot/extension-dapp` which supports many extensions like polkadot{js}, talisman, Nova-/Subwallet

The worker-api should support this as well

**Comment by clangenb** [comment]
Closed by #110
