### ISSUE TITLE
[worker-api] allow replay of TrustedGetters

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-js#109]
TrustedGetterSigned currently has no nonce and can be reused to poll balances once it is signed. While this may have to change in the future, we can temporarily leverage this to improve UX.

instead of:
```
  worker-api
    .getBalance(account, shard)
    .then((balance) => {
      console.log(
        `current account balance L2: ${balance} on shard ${incogniteeStore.shard}`,
      );
```
we could have `signBalanceGetter` and `sendBalanceGetter` (also, with support of #108 )

**Comment by clangenb** [comment]
Closed by #110
