### ISSUE TITLE
Rpc bazaar.getBusinesses(cid) call should expect argument in base58 format

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-js#25]
Right now, we have a mixture of base58 and hex formats for input/output arguments, I would suggests, that we keep it unified, maybe in base58?
This is the case:
Custom Rpc call: bazaar.getAllBusinesses(cid) expects hex format
Custom rpc call communities. communities.getAll() 
Returns to be determined
Gesell node client: list-businesses flag expects cid in base58 format
Gesell node client: get communities: returns communities in hex format

**Comment by brenzi** [comment]
wait for https://github.com/encointer/pallets/issues/54

**Comment by clangenb** [comment]
We can't change the format of the input of `rcp.bazaar.GetAllBusiness` this is automatically derived from the rust code. We could wrap the RPC at most.

Anyhow, I guess the current state, that it expects the strongly typed `CommunityIdentifier` is fine.
