### ISSUE TITLE
support new rpc functions in 0.8.0

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-js#41]
encointerBalances_getAllBalances
ceremonies_getReputations

https://github.com/encointer/encointer-node/releases/tag/v0.8.0

**Comment by clangenb** [comment]
Just for the records, support is already there, but as we did not define them explicitly in the types, we get the warning of `undecorated` rpc calls upon api initialisation.

**Comment by clangenb** [comment]
Done
